analyser/api/urls.py
from django.urls import path

from .views import WebAnalyserAPIView

app_name = 'analyser'

urlpatterns = [
    path('', WebAnalyserAPIView.as_view(), name='index-api'),
]

analyser/urls.py
from django.urls import path

from .views import ShowTableSummaryView, ShowTableSummaryViaAPIView

app_name = "analyser"

urlpatterns = [
    path('', ShowTableSummaryView.as_view(), name='index'),
    path('2', ShowTableSummaryViaAPIView.as_view(), name='index2'),
]

web_analyser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('analyser.urls', namespace='analyser')),


    path('api/', include('analyser.api.urls', namespace='analyser-api'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

analyser/models.py
from django.db import models

# Create your models here.

analyser/forms.py
from django import forms


class SearchForm(forms.Form):
    url = forms.URLField(widget=forms.URLInput(attrs={'placeholder': "Enter URL"}))

analyser/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.status import HTTP_400_BAD_REQUEST
from rest_framework.permissions import AllowAny

from .serializers import AnalysisSerializer, SearchSerializer

from ..utils import get_page_analysis


class WebAnalyserAPIView(APIView):
    """
    post:
    Get a valid url and return the analysis of the webpage associated with the url

    <pre>

    </pre>

    """
    permission_classes = (AllowAny, )
    search_serializer = SearchSerializer
    analysis_serializer = AnalysisSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        search_serializer = self.search_serializer(data=data)
        if search_serializer.is_valid(raise_exception=True):
            url = search_serializer.validated_data.get('url')
            result = get_page_analysis(url)
            analysis_serializer = self.analysis_serializer(instance=result)
            return Response(analysis_serializer.data)
        return Response(search_serializer.errors, status=HTTP_400_BAD_REQUEST)

analyser/views.py
from django.views.generic import FormView, TemplateView

from .forms import SearchForm
from .utils import get_page_analysis

# Create your views here.


class ShowTableSummaryView(FormView):
    """
    View that reload when searching
    """
    template_name = 'analyser/index.html'
    form_class = SearchForm

    def form_valid(self, form):
        url = form.cleaned_data.get('url')
        result = get_page_analysis(url)
        return self.render_to_response(self.get_context_data(form=form, result=result))


class ShowTableSummaryViaAPIView(TemplateView):
    """
    A view that conducts the searches on-page (without reloading)
    """
    template_name = 'analyser/index2.html'

    def get_context_data(self, **kwargs):
        context = super(ShowTableSummaryViaAPIView, self).get_context_data(**kwargs)
        context['form'] = SearchForm()
        return context

analyser/templates/analyser/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Web Analyser</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="author" content="colorlib.com">
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
        .s130 form {
            margin: auto;
        }

        .panel {
            background-color: #d9f1e3;
        }

        .panel-heading {
            background-color: #00ad5f;
            color: #fff;
        }

        a small {
            color: #fff;
        }

        #searching {
            display: none;
        }

        a.btn{
            margin: auto;
        }

    </style>
</head>
<body>
<div class="s130">
    <form action="" method="post">{% csrf_token %}
        <div class="inner-form">
            <div class="input-field first-wrap">
                <div class="svg-wrapper">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                    </svg>
                </div>
                {{ form.url }}
            </div>
            <div class="input-field second-wrap">
                <button class="btn-search" type="submit">Analyse</button>
            </div>
        </div>
        {% block links %}
        <a class="btn btn-default btn-success text-center" href="{% url 'analyser:index2' %}">Search (without reload)</a>
        {% endblock %}
        {% block result_area %}
            {% if result %}
                {% include 'analyser/result_section.html' %}
            {% endif %}
        {% endblock %}
    </form>
</div>
{#<script type="application/javascript" src="{% static 'js/jquery.min.js' %}"></script>#}
{#<script type="application/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>#}
{#<script src="{% static 'js/extention/choices.js' %}"></script>#}
{% block scripts %}{% endblock %}
</body>
</html>

analyser/templates/analyser/index2.html
{% extends 'analyser/index.html' %}

{% block links %}
        <a class="btn btn-default btn-success text-center" href="{% url 'analyser:index' %}">Search</a>
        {% endblock %}

{% block result_area %}
    <p id="searching">Searching...</p>
    <div id="result_area" style="display: none;">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="text-center">Result</h2>
                <p>Number of tables on page: <span id="no_of_table">{{ result.number_of_tables }}</span></p>
                <div class="panel-group" id="accordion">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="application/javascript">
        let form = document.forms[0];
        form.removeAttribute('action');
        form.onsubmit = function (e) {
            e.preventDefault();
            let searching = document.getElementById('searching');
            // Hide result area
            let result_area = document.getElementById('result_area');
            result_area.style.display = 'none';
            // Clear accordion
            document.getElementById('accordion').innerHTML = "";
            $.ajax({
                url: '{% url 'analyser-api:index-api' %}',
                data: $(form).serialize(),
                type: 'post',
                beforeSend: function(){
                    searching.style.display = 'block'
                }
            }).done(function (data) {
                console.log(data);
                document.getElementById('no_of_table').innerText = data.number_of_tables;
                let accordion = document.getElementById('accordion');
                for (var i=0; i<data.result_summary.length; i++){
                    let info = data.result_summary[i];
                    let panelHeading = createPanelHeading();
                    let panel = createPanel();
                    let panelTitle = createPanelTitle(info.index, info.number_of_rows);
                    let panelCollapse = createPanelCollapse(info.index, info.table_head);

                    panelHeading.appendChild(panelTitle);
                    panel.appendChild(panelHeading);
                    panel.appendChild(panelCollapse);
                    accordion.appendChild(panel);
                }
                searching.style.display = 'none';
                result_area.style.display = 'block';
            }).fail(function () {

            })
        };

        function createPanel(){
            let ele = document.createElement('div');
            ele.classList.add('panel');
            return ele;
        }

        function createPanelHeading(){
            let ele = document.createElement('div');
            ele.classList.add('panel-heading');
            return ele;
        }

        function createPanelTitle(index, number_of_rows){
            let title = document.createElement('h4');
            title.classList.add('panel-title');
            let link = document.createElement('a');
            link.setAttribute('data-toggle', 'collapse');
            link.setAttribute('data-parent', '#accordion');
            link.href = "#collapse" + index.toString();
            link.innerHTML = "Table " + index + " has " + number_of_rows.toString() + " row(s) <small>(Click here to view more)</small>";
            title.appendChild(link);
            return title;
        }

        function createPanelCollapse(index, table_head){
            let collapse = document.createElement('div');
            let body = document.createElement('div');
            collapse.id = 'collapse' + index.toString();
            collapse.classList.add('panel-collapse', 'collapse');
            body.classList.add('panel-body');
            if (table_head !== "None"){
                pre_ele = document.createElement('pre');
                pre_ele.innerText = table_head;
                body.appendChild(pre_ele);
            }
            else{
                body.innerHTML = "No table head definition found";
            }
            collapse.appendChild(body);
            return collapse
        }
    </script>
{% endblock %}

analyser/templates/analyser/result_section.html
<div class="row">
    <div class="col-lg-12">
        <h2 class="text-center">Result</h2>
        <p>Number of tables on page: {{ result.number_of_tables }}</p>
        <div class="panel-group" id="accordion">
            {% for table in result.result_summary %}
                <div class="panel">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ table.index }}">
                                Table {{ table.index }} has {{ table.number_of_rows }}
                                row{{ table.number_of_rows|pluralize }} <small>(Click to view table head definition)</small></a>
                        </h4>
                    </div>
                    <div id="collapse{{ table.index }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            {% if table.table_head != 'None' %}
                            <pre>
                                {{ table.table_head }}
                            </pre>
                            {% else %}
                                No table head definition found
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>